global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'erpc-local'
    static_configs:
      - targets:
          - 'host.docker.internal:4001'

  - job_name: 'erpc-x402-fly'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'erpc-x402-test.fly.dev:443'
        labels:
          environment: 'fly'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - alertmanager:9093
