#!/usr/bin/env bash
set -euo pipefail

root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$root"

out="${1:-review/repo-map.md}"
mkdir -p "$(dirname "$out")"

{
  echo "# Repo Map"
  echo
  echo "<!-- Generated by scripts/agent-harness/update-repo-map.sh. -->"
  echo
  scripts/review-repo-map.sh
} > "$out"

echo "Wrote $out"
