name: Logic Diagram

on:
  issue_comment:
    types: [created]

jobs:
  diagram:
    if: |
      github.event.issue.pull_request &&
      contains(fromJSON('["OWNER", "MEMBER"]'), github.event.comment.author_association) &&
      (contains(github.event.comment.body, '/generate-diagram') ||
       contains(github.event.comment.body, '/refresh-diagram'))
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Logic Diagram Action
        uses: with-logic/logic-diagram-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          document_id: 80090265-b8f3-4019-b0ff-5d1bc8577e70
        env:
          LOGIC_API_TOKEN: ${{ secrets.LOGIC_API_KEY }}
