name: prune

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Prune images
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch multi-platform package version SHAs
        id: multi-arch-digests
        run: |
          erpc=$(docker manifest inspect ghcr.io/erpc/erpc | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
          echo "multi-arch-digests=$erpc" >> $GITHUB_OUTPUT

      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: erpc
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "erpc"
          image-tags: "!latest !main !*.*.*"
          skip-shas: ${{ steps.multi-arch-digests.outputs.multi-arch-digests }}
          tag-selection: both
          cut-off: 0ms
          dry-run: true
